Email:
  address: <your.email@gmail.com>
  password: <your password>
  port: 587
  recipients: []
  server: smtp.gmail.com
Maintenance:
  backup:
    number: 1
    path: ~/MC_Backups
    schedule: ''
  complete_shutdown: ''
  schedule: ''
  update:
    allow_major_update: false
    schedule: ''
Minecraft:
  allocated_ram: 1024
  version:
    build: null
    install_date: ''
    major: null
    minor: null
    patch: null
    version_group: null
